### ISSUE TITLE
question: what is Nicomsoft OCR file format?

### ISSUE THREAD

**Issue by boomsya** [pixeltris/Ocr#1]
hi
maybe you know what is the file format Nicomsoft OCR used?
I have installed this OCR lib and see OCR languages files (*.lng) in folder Bin_common
I need to add Ukrainian language but I dont know in which file format need to do

**Comment by pixeltris** [comment]
I'm honestly not sure, it has been a long time since I touched this project and Nicomsoft wasn't that great. The implementation for it used by this project bypassed the free version. I can't remember a lot about it beyond that.

I would recommend using Google Vision (which I think is now called Vision AI or something) as it's very strong and always gave me the best output.

The second best for me was the in-built Windows 10 OCR engine which likely has the language you want. It is also fairly strong.

I imagine there are better OCR implementation now that AI has come a long way.

**Comment by boomsya** [comment]
thanks. 
I need offline version of OCR - application works with no internet connections. Think what I will try to work with Win10 OCR.
